name: nat
version: 0.1.0.0
github: 'nat-lang/nat'
license: BSD3
author: 'Alex Shilen'
maintainer: 'shilen.alexander@gmail.com'
copyright: '2022 Alex Shilen'

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/nat-lang/nat#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - pretty

  - mtl
  - containers
  - transformers
  - binary-tree  >= 0.0.9.0 && < 0.1.1.0
  - monad-gen

  - megaparsec
  - parser-combinators

  - haskeline
  - repline       >= 0.1.2.0
  - optparse-applicative

  - HaTeX

library:
  source-dirs:
    - src

executables:
  nat:
    main: Main.hs
    source-dirs:
      - src
      - exe
    other-modules: []
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  spec:
    defaults: hspec/hspec@main
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - hspec
      - HUnit
      - hspec-wai
      - hspec-wai-json
      - aeson
      - raw-strings-qq
      - nat
