name: interpreter
version: 0.1.0.0
github: 'githubuser/interpreter'
license: BSD3
author: 'Author name here'
maintainer: 'example@example.com'
copyright: '2022 Author name here'

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files- it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/interpreter#readme>

dependencies:
  - base >= 4.7 && < 5
  - servant
  - servant-server
  - aeson
  - attoparsec
  - base-compat
  - bytestring
  - containers
  - directory
  - data-default
  - http-api-data
  - http-client
  - http-media
  - http-types
  - mtl
  - string-conversions
  - text
  - transformers
  - wai
  - wai-logger
  - wai-extra
  - wai-cors
  - warp
  - blaze-html   >= 0.9.0.1 && < 0.10
  - blaze-markup >= 0.8.0.0 && < 0.9
  - cookie       >= 0.4.3   && < 0.5
  - js-jquery    >= 3.3.1   && < 3.4
  - lucid        >= 2.9.11  && < 2.12
  - random       >= 1.1     && < 1.3
  - servant-js   >= 0.9     && < 0.10
  - time         >= 1.6.0.1 && < 1.13
  - fast-logger
  - vector

  - monad-memo
  - pretty

  - ghc-paths
  - ghc
  - hashmap
  - parsec

library:
  source-dirs:
    - src
    - src/fragments

executables:
  interpreter-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - interpreter

tests:
  interpreter-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - interpreter
      - hspec
      - hspec-wai
      - hspec-wai-json
      - aeson
