version: "3.8"
services:
  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5433:5432'
  
  backend:
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST}
    ports:
      - '8001:80'
    build:
      context: ./src
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    volumes:
      - ./src/app:/app
      - ./src/start.sh:/start.sh
    command: '/start.sh'

volumes:
  app-db-data:

networks:
  traefik-public:
    # Allow setting it to false for testing
    external: ${TRAEFIK_PUBLIC_NETWORK_IS_EXTERNAL-true}
